requirements and possible adaptation
AccentDesign/modular_dotnet_boilerplate pull request #2
Opened 2022-09-05 11:20 UTC by rezabashiri

2022-09-06 08:31 UTC, craigvincent reviewed
Looks good dude.. as we said before in the EmergencyList meeting, I do like the overall approach, especially how easy mediatr makes it to apply different validation rules based on type & other behaviours. It looks like the event logging could be really helpful for auditing.

A few points overall:

Firstly, I know we've got the "auth" module included in the boilerplate, but it does feel like it would be sensible to have an example basic module included too. IMO it can be as small as one core entity with list/add functionality, just to demonstrate the the approach outside of the additional "fuzz" that auth brings.

Secondly, I think we need to ensure we're testing as much as possible. Perhaps if this wasn't going to be used for EmergencyList we could be more lenient, but with regards to EmergencyList code we need to be ensuring all important components are tested and we are confident they behave as expected, so it probably makes sense in this can ensuring that our unit tests start from the boilerplate.

Some superfluous code should probably be removed - for example Sms sending & File Upload. Unless either of this is actively being used to demonstrate something, I don't think we should include it, and risk the boilerplate becoming too bloated. Not only that, if we include them "because they'll be useful for EmergencyList" that may be more than a year way, and the requirements may have changed, or twilio's api layer might have been updated. We need to write tests for these too, so it's going to feel like increased effort which may just be discarded. 

There are quite a lot of stale references to the sample repo which inspired you throughout, I think I've tried to highlight in my comments, but it will be worth doing a general checkover the repo.

Some of the actions are failing, because I think they haven't yet been setup, I think I commented specifically on the SonarQube one, but we probably need to fix these, or decide which are relevant.

Just as a final thought, I'm sure we're going to find changes & improvements as we kick off EmergencyList based on this template, we should try and take time to revisit and think which changes should be applied back to the boilerplate in future 🙂 

Thanks for your hard work @rezabashiri 👍🏻

2022-09-06 08:31 UTC, craigvincent commented on .github/FUNDING.yml
> +open_collective: fluentpos
```suggestion
github: # Replace with a GitHub username
patreon: # Replace with a single Patreon username
open_collective: # Replace with a open collective username
```

This file can likely be removed.

2022-09-06 08:31 UTC, craigvincent commented on .github/workflows/dotnet.yml
> +      run: dotnet clean src/server/FluentPOS.sln -c Release && dotnet nuget locals all --clear
This action is failing and currently refences FluentPOS.sln

2022-09-06 08:31 UTC, craigvincent commented on .github/workflows/sonarqube.yml
> +          .\.sonar\scanner\dotnet-sonarscanner begin /k:"fluentpos_fluentpos" /o:"fluentpos" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
Fluentpos mentioned on this line

But more broadly, do we want to enable SonarQube to measure code quality? It may be the opportunity to try it as we can use the cloud service for free for public github repos. It was the topic of my only recent "show & tell" project, but as soon as we look at private repos, cost becomes a factor again! 💰

2022-09-06 08:31 UTC, craigvincent commented on CODE_OF_CONDUCT.md
> +https://www.contributor-covenant.org/translations.
While the code of conduct contains wise & sensible rules IMO, we might need to run this by @daveaccent & other knowledgeable folks to see if this should remain.

2022-09-06 08:31 UTC, craigvincent commented on CONTRIBUTING.md
> +- Squash your commits into a single commit with git's [interactive rebase](https://help.github.com/articles/interactive-rebase). Create a new branch if necessary.
There's really no need to advise this, as PR merging can do the squash on merge automatically :) and to be honest I prefer that (I've already applied squash-merging PRs on [AccentDesign/dotnet_routeoptimiser](https://github.com/AccentDesign/dotnet_routeoptimiser/commits/master) to trial it)

2022-09-06 08:31 UTC, craigvincent commented on LICENSE
> +SOFTWARE.
Is there enough of FluentPOS's code remaining for this to have to be present in the repo?

2022-09-06 08:31 UTC, craigvincent commented on src/server/API/appsettings.json
> +    "EnableVerification": true
Someone elses' ethereal dev mail inbox?

2022-09-06 08:31 UTC, craigvincent commented on src/server/Modules/Identity/Modules.Identity.Core/Entities/AccentRole.cs
> +// <copyright file="FluentRole.cs" company="AccentDesign">
```suggestion
// <copyright file="AccentRole.cs" company="AccentDesign">
```

2022-09-06 08:31 UTC, craigvincent commented on src/server/Modules/Identity/Modules.Identity.Core/Entities/FluentRoleClaim.cs
> +    public class FluentRoleClaim : IdentityRoleClaim<string>, IBaseEntity
```suggestion
    public class AccentRoleClaim : IdentityRoleClaim<string>, IBaseEntity
```

2022-09-06 08:31 UTC, craigvincent commented on workspace/fluentpos.code-workspace
> +{
Is this needed - its for vscode? also named fluentpos

2022-09-06 08:31 UTC, craigvincent commented on src/server/Shared/Shared.DTOs/Upload/UploadType.cs
> +namespace Shared.DTOs.Upload
Does this DTO have any relevance in our template?

2022-09-06 08:31 UTC, craigvincent commented on src/server/Shared/Shared.DTOs/Upload/UploadRequest.cs
> +{
Does this DTO have any relevance in our template?

2022-09-06 08:31 UTC, craigvincent commented on src/server/Shared/Shared.Core/Constants/RoleConstants.cs
> +        public const string Staff = "Staff";
Maybe need different sample roles as these still seem specific to the old domain?

2022-09-06 08:31 UTC, craigvincent commented on src/server/Shared/Shared.Core/Constants/Permissions.cs
> +    }
Maybe not all relevant?

2022-09-06 08:31 UTC, craigvincent commented on src/server/Shared/Shared.Core/Behaviors/ValidationBehavior.cs
> +    public class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
I do love how mediatr's pipeline behaviours take a large amount of pain out of these cross-cutting concerns

2022-09-06 08:31 UTC, craigvincent commented on docs/adding-extended-attribute-tutorial.md
> +```
A lot of mentions of fluentpos in this documentation

2022-09-06 08:31 UTC, craigvincent commented on docs/api-switching-database-provider-tutorial.md
> +fluentpos currently supports MSSQL & Postgres Dbs. Due to issues with schemas in EFCore's MySQL implementation, MySQL is not being used here.
```suggestion
This app currently supports MSSQL & Postgres Dbs. Due to issues with schemas in EFCore's MySQL implementation, MySQL is not being used here.
```

2022-09-06 09:43 UTC, rezabashiri commented
@craigvincent thanks for your in-detail checking out, most of your concerns are in actions and I didn't do anything on those as I should have known your idea about those actions, Do you think all of these are handy and useful? 
SonarQube 
Code scanning results
CodeQL

2022-09-12 10:04 UTC, craigvincent commented
Hey Reza, based on the previous comments I think there's some more stuff that requires action:

> Firstly, I know we've got the "auth" module included in the boilerplate, but it does feel like it would be sensible to have an example basic module included too. IMO it can be as small as one core entity with list/add functionality, just to demonstrate the the approach outside of the additional "fuzz" that auth brings.

To do

- [ ] Add a sample basic sample module

 

> Secondly, I think we need to ensure we're testing as much as possible. Perhaps if this wasn't going to be used for EmergencyList we could be more lenient, but with regards to EmergencyList code we need to be ensuring all important components are tested and we are confident they behave as expected, so it probably makes sense in this can ensuring that our unit tests start from the boilerplate.

To do
- [ ] Add tests to important core components to increase confidence and so we're able to improve & refactor with confidence
 

> Some superfluous code should probably be removed - for example Sms sending & File Upload. Unless either of this is actively being used to demonstrate something, I don't think we should include it, and risk the boilerplate becoming too bloated. Not only that, if we include them "because they'll be useful for EmergencyList" that may be more than a year way, and the requirements may have changed, or twilio's api layer might have been updated. We need to write tests for these too, so it's going to feel like increased effort which may just be discarded.

To do 

- [ ] Review unused code and remove where not needed in the near future


 
> There are quite a lot of stale references to the sample repo which inspired you throughout, I think I've tried to highlight in my comments, but it will be worth doing a general checkover the repo.

👍🏻 Thanks for looking through the repo for these

2022-09-13 06:23 UTC, rezabashiri commented
Thanks for your constructive and detailed feedback, 
1- I agree to provide a sample module to demonstrate how a module would look likes 
2- But not really happy about removing SMS and FileUpload, because boilerplate projects not only have to be universal but also provide general core functionalities of a modern system, look at https://github.com/aspnetboilerplate/aspnetboilerplate/tree/dev/src lots of libraries is being included from Owin to NHibernate and EntityFrameWork, Mongo, SignalR and.. , Maybe its better to have a short catch up upon this :)
3- About tests, I'm basically a TDD developer, and absolutely Tests are needed but because there were no any module in the system I didn't add any tests also main repo has not any but gonna add tests for the first module 
4- I had been looking for FluentPos references and removed lots of them except just GitHub actions because i wasn't sure which one of those you'd like to keep, though no worries gonna do deeper search to catch them all

2022-09-14 10:50 UTC, craigvincent commented
> 2- But not really happy about removing SMS and FileUpload, because boilerplate projects not only have to be universal but also provide general core functionalities of a modern system, look at https://github.com/aspnetboilerplate/aspnetboilerplate/tree/dev/src lots of libraries is being included from Owin to NHibernate and EntityFrameWork, Mongo, SignalR and.. , Maybe its better to have a short catch up upon this :)

Definitely happy to catch up on this further to see what's relevant :)

Just to clarify though, I don't think we want to be aiming for something that goes down the same route as aspnetboilerplate. We want a template solution which shows the use of modular monolith. As lean as possible, and focussing on demonstrating the structure and core components.

If we make it too large, with a small team such as ours the whole boilerplate will be out of date before we use it again otherwise, and there won't be time to manage it. 

If we want to introduce FileUploads or SMS handling, I'd suggest we pull these out as separate packages, when we know what we have a use for them, then they can then be isolated and well tested. For example, the SMS service currently in place uses Twilio, which means we won't use it on EmergencyList as Geoff has said we can't use it as an external dependency. I'm not even sure we have a steer that SMS notifications will be needed in EmergencyList in the future, I think it's outside of the initial scope (@geoffaccent ?) . This probably means such a feature is more than a year away, so this code will just become stale.

2022-09-14 13:45 UTC, rezabashiri commented
> > 2- But not really happy about removing SMS and FileUpload, because boilerplate projects not only have to be universal but also provide general core functionalities of a modern system, look at https://github.com/aspnetboilerplate/aspnetboilerplate/tree/dev/src lots of libraries is being included from Owin to NHibernate and EntityFrameWork, Mongo, SignalR and.. , Maybe its better to have a short catch up upon this :)
> 
> Definitely happy to catch up on this further to see what's relevant :)
> 
> Just to clarify though, I don't think we want to be aiming for something that goes down the same route as aspnetboilerplate. We want a template solution which shows the use of modular monolith. As lean as possible, and focussing on demonstrating the structure and core components.
> 
> If we make it too large, with a small team such as ours the whole boilerplate will be out of date before we use it again otherwise, and there won't be time to manage it.
> 
> If we want to introduce FileUploads or SMS handling, I'd suggest we pull these out as separate packages, when we know what we have a use for them, then they can then be isolated and well tested. For example, the SMS service currently in place uses Twilio, which means we won't use it on EmergencyList as Geoff has said we can't use it as an external dependency. I'm not even sure we have a steer that SMS notifications will be needed in EmergencyList in the future, I think it's outside of the initial scope (@geoffaccent ?) . This probably means such a feature is more than a year away, so this code will just become stale.

I can understand your concerns and doubts, consider that removing and purgings are so easy and can be done in a couple of minutes, probably better to keep those here till we move them into separate Repo. 
From another hand, boilerplate can be somehow general and universal and child repo takes or remove what they need. 

It needs more discussion and mind-storming, maybe in the next meeting :)

2022-09-16 13:52 UTC, rezabashiri commented
@craigvincent Hopefully your important concerns are met, and for sure could be developed more in future

2022-09-22 16:32 UTC, craigvincent requested changes
This is all looking really good @rezabashiri just some further renames & an English correction.

2022-09-22 16:32 UTC, craigvincent commented on src/server/Modules/Identity/Modules.Identity.Core/Entities/AccentRole.cs
> +// <copyright file="FluentRole.cs" company="AccentDesign">
Still applies

2022-09-22 16:32 UTC, craigvincent commented on src/server/Modules/Identity/Modules.Identity.Core/Entities/AccentRoleClaim.cs
> +// <copyright file="FluentRoleClaim.cs" company="AccentDesign">
Copyright needs adjusting

2022-09-22 16:32 UTC, craigvincent commented on src/server/Modules/Identity/Modules.Identity.Core/Entities/AccentUser.cs
> +// <copyright file="FluentUser.cs" company="AccentDesign">
another one here :)

2022-09-22 16:32 UTC, craigvincent commented on src/server/API/appsettings.json
> +    "EnableVerification": true
These are still wrong - and the details don't work either!

2022-09-22 16:32 UTC, craigvincent commented on src/server/API/appsettings.json
> +    "DisplayName": "Mukesh Murugan",
```suggestion
    "From": "boilerplate@accentdesign.co.uk",
    "Host": "smtp.ethereal.email",
    "Port": 587,
    "UserName": "jeffry27@ethereal.email",
    "Password": "9U2sJHZsxd8ekZF383",
    "DisplayName": "Accent Boilerplate",
```

I setup an account as part of testing if you want to use it :) ^^

2022-09-22 16:32 UTC, craigvincent commented on src/server/Modules/EmployeeManagement/Modules.EmployeeManagement.Infrastructure/Persistence/EmployeeManagementDbContext.cs
> +        public DbSet<Staff> Staves { get; set; }
Staves isn't English, probably needs to be `Staff` (which is a plural), or `StaffMembers` (and probably rename the entity to `StaffMember` to match)

2022-09-22 16:32 UTC, craigvincent commented on src/server/Modules/EmployeeManagement/Modules.EmployeeManagement/Controllers/StaffController.cs
> +}
```suggestion

namespace Modules.EmployeeManagement.Controllers;

[ApiVersion("1")]
public class StaffController : BaseController
{
    [HttpPost]
    public async Task<ActionResult> EmployStaffAsync(EmployStaffCommand command)
        => StatusCode((int)HttpStatusCode.Created, await Mediator.Send(command));
}
```

We could use the simpler syntax here if you wanted - but not important!

2022-09-22 16:32 UTC, craigvincent commented on src/server/Modules/EmployeeManagement/Modules.EmployeeManagement/Controllers/StaffController.cs
> +}
No logic in the controller, just simplicity ❤️ 🎉

2022-09-22 16:32 UTC, craigvincent commented on workspace/fluentpos.code-workspace
> +{
Bump - probably needs removing.

2022-09-26 11:55 UTC, craigvincent approved these changes
One small spelling mistake remains - otherwise looking good :)

2022-09-26 11:55 UTC, craigvincent commented on src/server/Modules/EmployeeManagement/Modules.EmployeeManagement.Core/Abstractions/IStaffManagementDbContext.cs
> +    DbSet<StaffMember> StaffMemebers { get; set; }
```suggestion
    DbSet<StaffMember> StaffMembers { get; set; }
```

2022-09-26 13:17 UTC, merged